image: jakzal/phpqa:php8.1

before_script:
    - composer install

cache:
    paths:
    - vendor/

stages:
    - analyze

phpstan:
    stage: analyze
    script:
        - phpstan analyse ./src
    allow_failure: false
