image: php:8.4-cli

services:
    - percona:ps-8.0.29-21
variables:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    DATABASE_URL: 'mysql://root:@percona:3306/symfony_demo_test'

before_script:
    - cd webapp
    - composer install
    - docker-php-ext-install mysqli pdo pdo_mysql
    - php bin/console --env=test doctrine:database:create
    - php bin/console --env=test doctrine:schema:create

cache:
    paths:
    - vendor/

stages:
    - analyze
    - test

phpstan:
    stage: analyze
    script:
        - phpstan analyse -c phpstan.dist.neon ./src
    allow_failure: false

phpunit:
    stage: test
    script:
        - php bin/phpunit --configuration phpunit.dist.xml
    allow_failure: false
