image: jakzal/phpqa:php8.4

before_script:
    - cd webapp
    - composer install

cache:
    paths:
    - vendor/

stages:
    - analyze
    - test

phpstan:
    stage: analyze
    script:
        - phpstan analyse -c phpstan.dist.neon ./src
    allow_failure: false

phpunit:
    stage: test
    script:
        - php bin/phpunit --configuration phpunit.dist.xml
    allow_failure: false
